# Generated by Django 4.2.16 on 2026-07-11 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Plant Categories',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('scientific_name', models.CharField(max_length=150)),
                ('image_url', models.URLField(max_length=500)),
                ('description', models.TextField()),
                ('water_requirement', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20)),
                ('sunlight', models.CharField(choices=[('Full Sun', 'Full Sun'), ('Partial Sun', 'Partial Sun'), ('Shade', 'Shade')], max_length=30)),
                ('soil_type', models.CharField(choices=[('Loamy', 'Loamy'), ('Sandy', 'Sandy'), ('Clay', 'Clay'), ('Well-drained', 'Well-drained')], max_length=30)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Advanced', 'Advanced')], max_length=20)),
                ('growth_duration', models.CharField(max_length=100)),
                ('best_season', models.CharField(max_length=100)),
                ('care_instructions', models.TextField()),
                ('fertilizer_tips', models.TextField()),
                ('harvesting_tips', models.TextField(blank=True)),
                ('prevention_tips', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_beginner', models.BooleanField(default=False)),
                ('is_low_maintenance', models.BooleanField(default=False)),
                ('weather_preference', models.JSONField(default=dict)),
                ('common_diseases', models.JSONField(default=list)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plants', to='garden.plantcategory')),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('ai_diagnosis', models.TextField()),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_scans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGarden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('custom_notes', models.TextField(blank=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='garden.plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden_plants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Garden Entry',
                'verbose_name_plural': 'User Garden Entries',
                'unique_together': {('user', 'plant')},
            },
        ),
        migrations.CreateModel(
            name='PlantCompanion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('GOOD', 'Good Companion'), ('BAD', 'Avoid Nearby')], max_length=10)),
                ('companion_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reverse_relationships', to='garden.plant')),
                ('primary_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='garden.plant')),
            ],
            options={
                'unique_together': {('primary_plant', 'companion_plant')},
            },
        ),
    ]
